### ISSUE TITLE
README.md out of date - no "setup" script

### ISSUE THREAD

**Issue by jimsorock** [kriasoft/relay-starter-kit#352]
"Getting Started" Section states to "Just [clone](https://github.com/kriasoft/relay-starter-kit/generate) the repo and run yarn install followed by yarn start:" but there is no script for "setup" in the package.json

**Comment by KingAxanthic** [comment]
same

**Comment by jvm986** [comment]
Looks like it was removed here https://github.com/kriasoft/relay-starter-kit/pull/341, possibly mistakenly

**Comment by koistya** [comment]
Fixed, thank you!
