### ISSUE TITLE
error while run yarn setup

### ISSUE THREAD

**Issue by Wacque** [kriasoft/relay-starter-kit#362]
error shows while run ```yarn setup```

```
Error: Your application tried to access dotenv, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```
- source commit id: fc27219295ca92925963237e3179f36093664488
- OS: macOS 13.1 (22C65), apple chip
- yarn: yarn@4.0.0-rc.39
- node: v18.5.0
- npm: 8.12.1

**Comment by koistya** [comment]
@Wacque thanks for the report! Just fixed it in #363
